---
- name: Preparing both servers
  hosts: all
  become: true
  vars_prompt:
      #Prompts user for username to delete
    - name: username
      prompt: What is the username you want to add?
      private: no

  tasks:

  - name: Creating the user 
    user:
      name:  "{{ username }}"
      shell: /bin/bash
      group: admin
      append: yes
