---
rpi-controller:
  hosts:
    pi-controller:
      ansible_host: pi-controller   # hostname defined in /etc/hosts
  vars:
      ansible_connection: ssh
      ansible_user: [username]

rpi-nodes:
  hosts:
    pi-node01:
      ansible_host: pi-node01   # hostname defined in /etc/hosts
  vars:
      ansible_connection: ssh
      ansible_user: [username]
