---
rpi-controller:
  hosts:
    pi-controller:
      ansible_host: [IP of host]
  vars:
      ansible_connection: ssh
      ansible_user: [user]
      ansible_password: !vault |
          $ANSIBLE_VAULT;[hash]

rpi-nodes:
  hosts:
    pi-node01:
      ansible_host: [IP of host]
  vars:
      ansible_connection: ssh
      ansible_user: [user]
      ansible_password: !vault |
          $ANSIBLE_VAULT;[hash]